project:
  type: website
  output-dir: _site

freeze: true

website:
  title: "Cameron Wimpy"
  site-url: "https://cwimpy.com"
  favicon: "favicon.ico"
  search:
    location: navbar
    type: overlay
  google-analytics: "G-TYNMV5ZKBT"
  back-to-top-navigation: true
  llms-txt: true
  twitter-card:
    image: "images/profile.png"
    card-style: summary
    creator: "@camwimpy"
  open-graph:
    title: "Dr. Cameron Wimpy"
    description: "Political Science Research & Teaching"
    image: "images/profile.png"
  navbar:
    pinned: true
    right:
      - href: posts/index.qmd
        text: Posts
      - href: research.qmd
        text: Research
      - href: software.qmd
        text: Software
      # - href: teaching.qmd
      #   text: Teaching
      - href: cv.qmd
        text: CV
      - href: now.qmd
        text: Now
      - icon: rss
        href: posts/index.xml
        aria-label: RSS
  page-footer:
    left: |
      © 2026 Cameron Wimpy ∙ Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org)
    center: |
      <a href="uploads/cv-wimpy.pdf">{{< ai cv >}}</a>
      <a href="mailto:{{< var email >}}">{{< fa envelope >}}</a>
      <a href="https://github.com/cwimpy" rel="me">{{< fa brands github >}}</a>
      <a href="{{< var scholar >}}">{{< ai google-scholar >}}</a>
      <a href="{{< var linkedin >}}" rel="me">{{< fa brands linkedin >}}</a>
      <a href="https://orcid.org/{{< var orcid >}}" rel="me">{{< ai orcid >}}</a>
      <a href="{{< var twitter >}}" rel="me">{{< fa brands x-twitter >}}</a>
      <a href="/posts/index.xml">{{< fa rss >}}</a>
    right: |
      <a href="/contact.html">Contact</a>

format:
  html:
    theme:
      light: [journal, styles.scss]
      dark: [journal, custom-dark.scss]
    page-navigation: true
    anchor-sections: true
    smooth-scroll: true
    footnotes-hover: true
    code-copy: true
    lightbox: true

filters:
  - fontawesome

bibliography: publications.bib