project:
  type: website
  output-dir: _site
  resources:
    - "files/"

website:
  title: "Cameron Wimpy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: files/cv.pdf
        text: CV
  favicon: "images/favicon.ico"
  page-footer:
    left: "© 2025 Cameron Wimpy"
    right:
      - icon: github
        href: https://github.com/cwimpy
      - icon: envelope
        href: "mailto:cwimpy@astate.edu"

format:
  html:
    theme: journal
    css: styles.css
    toc: true