---
title: "Resources"
subtitle: "PLSC 66003: Advanced Political Analysis"
---

::: {.content-container}

## Software Setup

Install these before the first class:

- [R](https://cran.r-project.org/) (latest version)
- [RStudio](https://posit.co/download/rstudio-desktop/) or [Positron](https://positron.posit.co/)
- [Quarto](https://quarto.org/docs/get-started/)

### Required packages

```r
install.packages(c(
  "tidyverse", "modelsummary", "fixest",
  "marginaleffects", "here", "quarto", "tinytable"
))
```

---

## Textbooks and References

### Primary

- Wickham, Cetinkaya-Rundel, and Grolemund. [R for Data Science](https://r4ds.hadley.nz/) (2e, free online)
- Imai. [Quantitative Social Science](https://press.princeton.edu/books/paperback/9780691175461/quantitative-social-science)

### Supplementary

- Huntington-Klein. [The Effect](https://theeffectbook.net/) (free online)
- James et al. [An Introduction to Statistical Learning](https://www.statlearning.com/) (free online)
- Healy. [Data Visualization: A Practical Introduction](https://socviz.co/) (free online)
- Arel-Bundock. [marginaleffects documentation](https://marginaleffects.com/)

---

## R Resources

### Getting started

- [RStudio Primers](https://posit.cloud/learn/primers) -- interactive tutorials
- [Posit Cheatsheets](https://posit.co/resources/cheatsheets/) -- one-page references for tidyverse packages

### Data wrangling

- [dplyr documentation](https://dplyr.tidyverse.org/)
- [tidyr documentation](https://tidyr.tidyverse.org/)
- [readr documentation](https://readr.tidyverse.org/)

### Visualization

- [ggplot2 documentation](https://ggplot2.tidyverse.org/)
- [R Graph Gallery](https://r-graph-gallery.com/) -- examples with code
- [Cedric Scherer's ggplot2 tutorial](https://www.cedricscherer.com/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/)

### Tables and output

- [modelsummary documentation](https://modelsummary.com/)
- [tinytable documentation](https://vincentarelbundock.github.io/tinytable/)

### Quarto

- [Quarto documentation](https://quarto.org/docs/guide/)
- [Quarto for academics](https://quarto.org/docs/blog/posts/2023-05-22-quarto-for-academics/)

---

## Getting Help

1. **Check the documentation** -- most R functions have excellent help files (type `?function_name`)
2. **Search online** -- [Stack Overflow](https://stackoverflow.com/questions/tagged/r) and [Posit Community](https://forum.posit.co/) are excellent
3. **Ask me** -- come to office hours or email me

:::
